### ISSUE TITLE
Network performance is extremely poor inside the container due to some interaction with receive side coalescing on a Windows host

### ISSUE THREAD

**Issue by doctorpangloss** [microsoft/Windows-Containers#145]
Downloads inside a container are very slow, indicating a serious flaw with the default network configuration. They cap at about 500kB/s-1MB/s, it varies for different users and has persisted for at least 4 years, as lately as 20H2 the last version to support process isolation mode: https://github.com/docker/for-win/issues/698

Executing the following workaround on the host and restarting the host fixes the issue:

```
powershell "Get-NetAdapterRSC | Disable-NetAdapterRSC"
```

You might want to notify the Windows feature installer team to do this automatically the first time a container is run on a Windows 10 machine.

The issue exists in all versions of Windows, including Server 2022.

**Comment by Hvid** [comment]
I'm having the same issue on 2022. Disabling RSC fixes it.

**Comment by wagnerscastle** [comment]
We've had this problem with 2019 and 2022.   Confirmed this "fixes" the issue at the cost of disabling RSC.

**Comment by daschott** [comment]
Thanks for reporting this -- will follow up internally on the observations here. Which network mode is being used here? NAT? Also, is the container host an Azure VM, a physical machine, or an on-premise VM?

I am not aware of anything breaking when disabling this (besides the feature itself), so this should be a viable workaround until the network perf issues are fixed in Server 2022.

**Comment by Hvid** [comment]
We're using on prem VMs hosted in VMWare using NAT network.

**Comment by doctorpangloss** [comment]
> Thanks for reporting this -- will follow up internally on the observations here. Which network mode is being used here? NAT? Also, is the container host an Azure VM, a physical machine, or an on-premise VM?
> 
> I am not aware of anything breaking when disabling this (besides the feature itself), so this should be a viable workaround until the network perf issues are fixed in Server 2022.

The issue has existed for 5 years now. Nothing was fixed in 2022.

**Comment by daschott** [comment]
@Hvid thank you for confirming, this issue is still being investigated and I will circle back here when I hear back from owners of relevant areas.

**Comment by ghost** [comment]
This issue has been open for 30 days with no updates.
@daschott, please provide an update or close this issue.

**Comment by cwilhit** [comment]
For reference, MSFT internal 38481005 is tracking this investigation.

**Comment by slonopotamus** [comment]
This possibly means that reporters are not providing enough info to reproduce the issue.

P.S. I am *not* experiencing it either.

**Comment by cwilhit** [comment]
Hi, we have tried to repro this as well too on our end and have unable to reproduce it so far. @doctorpangloss I presume you've moved on from this as well, although I see you update the issue's original message in January to callout this was still being experienced on Windows Server 2022. If you have the build number and docker info associated with when you were seeing this, please share it. Otherwise we're not going to have much to go off of and the issue will be closed.

**Comment by slonopotamus** [comment]
Ideally, this bugreport should be like:
1. Install vanilla Windows in a VM
2. Do this
3. Do that
4. Observe slow networking

But in its current state, I'd just close it as NOTENOUGHINFO.

**Comment by doctorpangloss** [comment]
> we have tried to repro this as well too on our end and have unable to reproduce it so far

This is a good place to write and document automated Windows container tests

https://k8s-testgrid.appspot.com/google-windows#gce-windows-20h2-1.23&show-stale-tests=

You could add an e2e test showing a download from an Internet gateway transiting external host at high speed to close the issue. As long as this issue isn't deleted as least people will know what the workaround is.

**Comment by doctorpangloss** [comment]
I don't think the issue is resolved. I'm not sure how or why it occurs, but it's real.

**Comment by spectras** [comment]
> Ideally, this bugreport should be like:
> 
> 1. Install vanilla Windows in a VM
> 2. Do this
> 3. Do that
> 4. Observe slow networking
> 
> But in its current state, I'd just close it as NOTENOUGHINFO.

It is not so easy. In our environment, the install is fully automated. Automation creates VMs, installs the system (Windows 22H1), deploys Docker in it, everything is fully controlled and reproducible. Yet:
- Some VMs exhibit the problem, some do not (I would say about ⅓ of built VMs are affected).
- Some VMs do not have the problem, sometimes for weeks, then suddenly it appears.

Only reliable workaround so far is disabling RSC. Since we added that step to automation we have not seen the problem all.
