### ISSUE TITLE
Windows Server Containers hard link limit issue  

### ISSUE THREAD

**Issue by immuzz** [microsoft/Windows-Containers#38]
Error: An attempt was made to create more links on a file than the file system supports. More details : https://github.com/moby/moby/issues/40511

**Comment by immuzz** [comment]
This is a known issue. It has been fixed in Windows OS and backported to Windows Server 2019 (1809 & LTSC), 19H1 and 20H1(2004). This will be part of July 2020 Windows Server update.

**Comment by wumingcp** [comment]
Hi @immuzz, I still faced the same issue when using Windows Server version 17763.1339.2007101755, can you help on this? thanks

## Docker info:
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 74
Server Version: 18.09.7
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file local logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1339)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 14GiB
Name: 3023k8s00000090
ID: P6G5:RWOA:UBKZ:7CVW:6JXR:2BCW:H7TK:5NYR:H447:M7PI:WLBA:PT23
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

## Computer Information:
WindowsBuildLabEx                                       : 17763.1.amd64fre.rs5_release.180914-1434
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : ServerDatacenter
WindowsInstallationType                                 : Server
WindowsInstallDateFromRegistry                          : 8/4/2020 7:08:57 AM
WindowsProductId                                        : 00430-00000-00000-AA148
WindowsProductName                                      : Windows Server 2019 Datacenter
WindowsRegisteredOrganization                           :
WindowsRegisteredOwner                                  :
WindowsSystemRoot                                       : C:\windows
WindowsVersion                                          : 1809
BiosCharacteristics                                     : {4, 7, 9, 11...}
BiosBIOSVersion                                         : {VRTUAL - 6001702, Intel(R) Xeon(R) CPU E5-2673 v3 @
                                                          2.40GHz, Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz, Intel(R)
                                                          Xeon(R) CPU E5-2673 v3 @ 2.40GHz...}
BiosBuildNumber                                         :
BiosCaption                                             : Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
BiosCodeSet                                             :
BiosCurrentLanguage                                     : enUS
BiosDescription                                         : Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
BiosEmbeddedControllerMajorVersion                      :
BiosEmbeddedControllerMinorVersion                      :
BiosFirmwareType                                        : Bios
BiosIdentificationCode                                  :
BiosInstallableLanguages                                : 1
BiosInstallDate                                         :
BiosLanguageEdition                                     :
BiosListOfLanguages                                     : {enUS}
BiosManufacturer                                        : American Megatrends Inc.
BiosName                                                : Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz
BiosOtherTargetOS                                       :
BiosPrimaryBIOS                                         : True
BiosReleaseDate                                         : 6/2/2017 12:00:00 AM
BiosSeralNumber                                         : 0000-0000-2543-5316-6737-8868-66
BiosSMBIOSBIOSVersion                                   : 090007
BiosSMBIOSMajorVersion                                  : 2
BiosSMBIOSMinorVersion                                  : 3
BiosSMBIOSPresent                                       : True
BiosSoftwareElementState                                : Running
BiosStatus                                              : OK
BiosSystemBiosMajorVersion                              :
BiosSystemBiosMinorVersion                              :
BiosTargetOperatingSystem                               : 0
BiosVersion                                             : VRTUAL - 6001702
CsAdminPasswordStatus                                   : Unknown
CsAutomaticManagedPagefile                              : False
CsAutomaticResetBootOption                              : True
CsAutomaticResetCapability                              : True
CsBootOptionOnLimit                                     : 0
CsBootOptionOnWatchDog                                  : 0
CsBootROMSupported                                      : True
CsBootStatus                                            : {0, 0, 0, 0...}
CsBootupState                                           : Normal boot
CsCaption                                               : 3023k8s00000090
CsChassisBootupState                                    : Safe
CsChassisSKUNumber                                      :
CsCurrentTimeZone                                       : 0
CsDaylightInEffect                                      :
CsDescription                                           : AT/AT COMPATIBLE
CsDNSHostName                                           : 3023k8s00000090
CsDomain                                                : WORKGROUP
CsDomainRole                                            : StandaloneServer
CsEnableDaylightSavingsTime                             : True
CsFrontPanelResetStatus                                 : Unknown
CsHypervisorPresent                                     : True
CsInfraredSupported                                     : False
CsInitialLoadInfo                                       :
CsInstallDate                                           :
CsKeyboardPasswordStatus                                : Unknown
CsLastLoadInfo                                          :
CsManufacturer                                          : Microsoft Corporation
CsModel                                                 : Virtual Machine
CsName                                                  : 3023k8s00000090
CsNetworkAdapters                                       : {Ethernet 2, vEthernet (nat), vEthernet (Ethernet 2)}
CsNetworkServerModeEnabled                              : True
CsNumberOfLogicalProcessors                             : 4
CsNumberOfProcessors                                    : 1
CsProcessors                                            : {Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz}
CsOEMStringArray                                        : {[MS_VM_CERT/SHA1/9b80ca0d5dd061ec9da4e494f4c3fd1196270c22],
                                                          00000000000000000000000000000000, To be filed by MSFT}
CsPartOfDomain                                          : False
CsPauseAfterReset                                       : 3932100000
CsPCSystemType                                          : Desktop
CsPCSystemTypeEx                                        : Desktop
CsPowerManagementCapabilities                           :
CsPowerManagementSupported                              :
CsPowerOnPasswordStatus                                 : Unknown
CsPowerState                                            : Unknown
CsPowerSupplyState                                      : Safe
CsPrimaryOwnerContact                                   :
CsPrimaryOwnerName                                      :
CsResetCapability                                       : Other
CsResetCount                                            : -1
CsResetLimit                                            : -1
CsRoles                                                 : {LM_Workstation, LM_Server, NT, Server_NT}
CsStatus                                                : OK
CsSupportContactDescription                             :
CsSystemFamily                                          :
CsSystemSKUNumber                                       :
CsSystemType                                            : x64-based PC
CsThermalState                                          : Other
CsTotalPhysicalMemory                                   : 15031914496
CsPhyicallyInstalledMemory                              : 14680064
CsUserName                                              :
CsWakeUpType                                            : PowerSwitch
CsWorkgroup                                             : WORKGROUP
OsName                                                  : Microsoft Windows Server 2019 Datacenter
OsType                                                  : WINNT
OsOperatingSystemSKU                                    : DatacenterServerEdition
OsVersion                                               : 10.0.17763
OsCSDVersion                                            :
OsBuildNumber                                           : 17763
OsHotFixes                                              : {KB4565625, KB4558997, KB4558998}
OsBootDevice                                            : \Device\HarddiskVolume1
OsSystemDevice                                          : \Device\HarddiskVolume2
OsSystemDirectory                                       : C:\windows\system32
OsSystemDrive                                           : C:
OsWindowsDirectory                                      : C:\windows
OsCountryCode                                           : 1
OsCurrentTimeZone                                       : 0
OsLocaleID                                              : 0409
OsLocale                                                : en-US
OsLocalDateTime                                         : 8/26/2020 8:00:35 AM
OsLastBootUpTime                                        : 8/4/2020 7:13:02 AM
OsUptime                                                : 22.00:47:32.9988546
OsBuildType                                             : Multiprocessor Free
OsCodeSet                                               : 1252
OsDataExecutionPreventionAvailable                      : True
OsDataExecutionPrevention32BitApplications              : True
OsDataExecutionPreventionDrivers                        : True
OsDataExecutionPreventionSupportPolicy                  : OptOut
OsDebug                                                 : False
OsDistributed                                           : False
OsEncryptionLevel                                       : 256
OsForegroundApplicationBoost                            : Maximum
OsTotalVisibleMemorySize                                : 14679604
OsFreePhysicalMemory                                    : 11573136
OsTotalVirtualMemorySize                                : 22969908
OsFreeVirtualMemory                                     : 19916008
OsInUseVirtualMemory                                    : 3053900
OsTotalSwapSpaceSize                                    :
OsSizeStoredInPagingFiles                               : 8290304
OsFreeSpaceInPagingFiles                                : 8274488
OsPagingFiles                                           : {D:\pagefile.sys}
OsHardwareAbstractionLayer                              : 10.0.17763.1131
OsInstallDate                                           : 8/4/2020 7:08:57 AM
OsManufacturer                                          : Microsoft Corporation
OsMaxNumberOfProcesses                                  : 4294967295
OsMaxProcessMemorySize                                  : 137438953344
OsMuiLanguages                                          : {en-US}
OsNumberOfLicensedUsers                                 : 0
OsNumberOfProcesses                                     : 175
OsNumberOfUsers                                         : 1
OsOrganization                                          :
OsArchitecture                                          : 64-bit
OsLanguage                                              : en-US
OsProductSuites                                         : {TerminalServices, DatacenterEdition,
                                                          TerminalServicesSingleSession}
OsOtherTypeDescription                                  :
OsPAEEnabled                                            :
OsPortableOperatingSystem                               : False
OsPrimary                                               : True
OsProductType                                           : Server
OsRegisteredUser                                        :
OsSerialNumber                                          : 00430-00000-00000-AA148
OsServicePackMajorVersion                               : 0
OsServicePackMinorVersion                               : 0
OsStatus                                                : OK
OsSuites                                                : {TerminalServices, DatacenterEdition,
                                                          TerminalServicesSingleSession}
OsServerLevel                                           : FullServer
KeyboardLayout                                          : en-US
TimeZone                                                : (UTC) Coordinated Universal Time
LogonServer                                             : \\3023k8s00000090
PowerPlatformRole                                       : Desktop
HyperVisorPresent                                       : True
HyperVRequirementDataExecutionPreventionAvailable       :
HyperVRequirementSecondLevelAddressTranslation          :
HyperVRequirementVirtualizationFirmwareEnabled          :
HyperVRequirementVMMonitorModeExtensions                :
DeviceGuardSmartStatus                                  : Off
DeviceGuardRequiredSecurityProperties                   :
DeviceGuardAvailableSecurityProperties                  :
DeviceGuardSecurityServicesConfigured                   :
DeviceGuardSecurityServicesRunning                      :
DeviceGuardCodeIntegrityPolicyEnforcementStatus         : AuditMode
DeviceGuardUserModeCodeIntegrityPolicyEnforcementStatus : AuditMode

## Error message:
Failed to pull image "opsppesynck8s.azurecr.io/ops-sync-service-ppe:v3.186743": [rpc error: code = Unknown desc = failed to register layer: re-exec error: exit status 1: output: time="2020-08-26T07:25:54Z" level=error msg="hcsshim::ImportLayer failed in Win32: An attempt was made to create more links on a file than the file system supports. (0x476) path=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\b41d139e0f144ee0c8a78820d8a8a33ad60963da14a16ccfd11605819ad33f99 folder=C:\\ProgramData\\docker\\tmp\\hcs944415779" hcsshim::ImportLayer failed in Win32: An attempt was made to create more links on a file than the file system supports. (0x476) path=\\?\C:\ProgramData\docker\windowsfilter\b41d139e0f144ee0c8a78820d8a8a33ad60963da14a16ccfd11605819ad33f99 folder=C:\ProgramData\docker\tmp\hcs944415779, rpc error: code = Unknown desc = failed to register layer: re-exec error: exit status 1: output: time="2020-08-26T07:26:19Z" level=error msg="hcsshim::ImportLayer failed in Win32: An attempt was made to create more links on a file than the file system supports. (0x476) path=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\67674cf0eb3ad16a8c123087e68087a2866efd51345468a522d65b47c711fec3 folder=C:\\ProgramData\\docker\\tmp\\hcs264831499" hcsshim::ImportLayer failed in Win32: An attempt was made to create more links on a file than the file system supports. (0x476) path=\\?\C:\ProgramData\docker\windowsfilter\67674cf0eb3ad16a8c123087e68087a2866efd51345468a522d65b47c711fec3 folder=C:\ProgramData\docker\tmp\hcs264831499, rpc error: code = Unknown desc = Error response from daemon: Get https://opsppesynck8s.azurecr.io/v2/ops-sync-service-ppe/manifests/v3.186743: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.]

**Comment by junneyang** [comment]
> This is a known issue. It has been fixed in Windows OS and backported to Windows Server 2019 (1809 & LTSC), 19H1 and 20H1(2004). This will be part of July 2020 Windows Server update.

which update should we use to install, thanks 
we use windows server 2019(1809)

**Comment by eglookz** [comment]
> > This is a known issue. It has been fixed in Windows OS and backported to Windows Server 2019 (1809 & LTSC), 19H1 and 20H1(2004). This will be part of July 2020 Windows Server update.
> 
> which update should we use to install, thanks
> we use windows server 2019(1809)

Hello! Any news?
