### ISSUE TITLE
Containers in hyperv isolation can only partly access mounted network share

### ISSUE THREAD

**Issue by tfenster** [microsoft/Windows-Containers#87]
We have Azure VMs with Windows Server 2019 (2004) where we mount an Azure File Share with the following PowerShell function

```
param(
    [Parameter(Mandatory = $True)]
    [string]
    $storageAccountName,

    [Parameter(Mandatory = $True)]
    [string]
    $storageAccountKey,

    [Parameter(Mandatory = $False)]
    [string]
    $driveLetter = "S"
)

$secpassword = ConvertTo-SecureString $storageAccountKey -AsPlainText -Force
$creds = New-Object System.Management.Automation.PSCredential("Azure\$storageAccountName", $secpassword)
New-SmbGlobalMapping -RemotePath "\\$storageAccountName.file.core.windows.net\share" -Credential $creds -LocalPath "$($driveLetter):" -Persistent $true -RequirePrivacy $true
Invoke-Expression "icacls.exe $($driveLetter):\ /grant 'Everyone:(OI)(CI)(F)'"
```

After that, we can bind mount the s drive into containers like this:

```
docker run -v s:\:c:\share --isolation process -ti --rm mcr.microsoft.com/windows/servercore:2004 powershell
```

On the share we have in a subfolder a file called `test.txt` with a simple content of `test`. I can verify that it works with this:

```
PS C:\> cat share\product-apps\opplus\test.txt
test
```

If I do the exact same thing in hyperv isolation, the following happens:
```
PS C:\> docker run -v s:\:c:\share --isolation hyperv -ti --rm mcr.microsoft.com/windows/servercore:2004 powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.   

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\> cat share\product-apps\opplus\test.txt
cat : Cannot find path 'C:\share\product-apps\opplus\test.txt' because it does not exist.
At line:1 char:1
+ cat share\product-apps\opplus\test.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\share\product-apps\opplus\test.txt:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

The access in general doesn't seem to be a problem because this works:
```
PS C:\> dir share\product-apps\opplus         

    Directory: C:\share\product-apps\opplus

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/19/2021  12:40 PM              4 test.txt
```

I am not sure if it just looks similar or it is actually related, but #85 describes something similar. We also have the same setup on Windows Server 2019 (1809) where it works

Some more information in case you need it:

```
PS C:\> docker info
Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 10
  Paused: 0
  Stopped: 1
 Images: 30
 Server Version: 19.03.13
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: active
  NodeID: cefso13dli26r6q336k1xvn2d
  Is Manager: false
  Node Address: 10.0.4.6
  Manager Addresses:
   10.0.3.4:2377
   10.0.3.6:2377
   10.0.3.7:2377
 Default Isolation: process
 Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows Server Datacenter Version 2004 (OS Build 19041.685)
 OSType: windows
 Architecture: x86_64
 CPUs: 4
 Total Memory: 32GiB
 Name: worker000002
 Docker Root Dir: F:\dockerdata
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
PS C:\> docker version
Client:
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.12
 Git commit:        0ed913b8-
 Built:             07/28/2020 16:36:03
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Mirantis Container Runtime
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       5b5efb2d49
  Built:            11/12/2020 21:31:44
  OS/Arch:          windows/amd64
  Experimental:     false
```

Please let me know if you need any other input

**Comment by tfenster** [comment]
@vrapolinario @weijuans-msft Any feedback on this? We are getting closer to the point where we need to update the environments to 2004. If it helps, I can create a support request for Azure support, I just have very mixed experience with their Docker knowledge, to put it politely

**Comment by weijuans-msft** [comment]
@tfenster Have you tried mapping a local drive or folder on v2004 with Hyper-V isolation on the VM?

I tried v2004 with Hyper-V isolation or without on my Windows 10 machines mapping a local folder (c:\tmp) and it worked fine. I am trying to see if the issue happens because the host VM is on Azure, or is it because you are using Azure File, or maybe combination of the two.

I am also curious why you needed Hyper-V isolation. My guess is you wanted to be able to run containers not in the same version of v2004. Is that correct?

**Comment by tfenster** [comment]
@weijuans-msft 
> @tfenster Have you tried mapping a local drive or folder on v2004 with Hyper-V isolation on the VM?

Yes, that works


> I tried v2004 with Hyper-V isolation or without on my Windows 10 machines mapping a local folder (c:\tmp) and it worked fine. I am trying to see if the issue happens because the host VM is on Azure, or is it because you are using Azure File, or maybe combination of the two.

My guess is Azure File Share  because local folders work and we have what looks to me like a very similar issue in #85. I can't however prove that as we are 100% on Azure, so I can't try other cloud vendors or OnPrem


> I am also curious why you needed Hyper-V isolation. My guess is you wanted to be able to run containers not in the same version of v2004. Is that correct?
Three scenarios:
1. We have encoding issues when running in process isolation, e.g. with German special characters like "umlauts". We can't solve that on the host as we also support other languages with special characters
2. We are forced to sometimes use quite old 32bit applications in the containers which also seem to have encoding issues or something like it
3. As you say, we sometimes have images where the creators don't offer 2004 images. The most "prominent" example probably is traefik (see https://github.com/docker-library/official-images/issues/9198#issuecomment-737477765, https://github.com/docker-library/official-images/issues/9198#issuecomment-737530852 and https://github.com/traefik/traefik-library-image/pull/2 for the reasons). We are getting better at avoiding that but we still sometimes need the fallback

**Comment by tfenster** [comment]
@weijuans-msft btw, if that helps, I would be happy to create a clean repro environment on Azure as we have basically everything automated, so you can take a look. Of course without any connections to our systems or customer data, so there wouldn't be data security of confidentiality issues

**Comment by weijuans-msft** [comment]
Thanks @tfenster. We are still chasing our engineers on this. Will let them know this offer. If they need it, will let you know. Today is our org's Monthly Day of Learning hence folks are heads-down on learning (vs. doing work :) ).

**Comment by weijuans-msft** [comment]
@tfenster It seems this is related to a bug that some other customers reported for the v2004 release. It is fixed and released in 2021.2C which should be last week. Can you get the latest container host and container image and test it?

Our engineers believe the other issue #85 is different.  Please try it with the latest updates and see it is fixed or not. If not, we could use your help to set up an repro environment.

For MSFT folks, the bug number is 30163731 "Cannot share folder into Hyper-V isolated container when folder sits on Azure Files-backed file share".

**Comment by tfenster** [comment]
@weijuans-msft I have tested and now see a different error message, but it still doesn't work. However get-hotfix returns the following, so it looks like the fix you talk about is not yet available on the Azure images? Do you have a KB number?

```
PS [worker000001]:C:\Users\vm-administrator> get-hotfix

Source        Description      HotFixID      InstalledBy          InstalledOn
------        -----------      --------      -----------          -----------
worker000001  Update           KB4601050                          2/5/2021 12:00:00 AM
worker000001  Security Update  KB4598481                          2/5/2021 12:00:00 AM
worker000001  Security Update  KB4601319                          2/5/2021 12:00:00 AM
```

Maybe that also helps, this is the OS version output, showing 2004

```
PS [worker000001]:C:\Users\vm-administrator> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.19041.0 Microsoft Windows NT 10.0.19041.0
```

**Comment by tfenster** [comment]
@weijuans-msft Just FYI: I tried again, still the same hotfixes on Azure VMs, unsurprisingly still the same results

**Comment by weijuans-msft** [comment]
@tfenster I checked with our servicing team and learned that fix to the bug 30163731 is in this,
https://support.microsoft.com/en-us/topic/february-24-2021-kb4601382-os-builds-19041-844-and-19042-844-preview-1a7ed2b4-017d-2644-a1e8-dd6bf14cba76. It's released in the so called "2c", the 3rd week of February. There was no container image rebuilt with this fix as we only rebuild the container images in "B" releases (2nd week of the month normally). But it should be in this month's B release "3B", which is this week. There should be a new Azure VM with this fix later on as well.

**Comment by tfenster** [comment]
@weijuans-msft ok, then I'll wait for that one. Do I only need the new container image or must the fix also appear on the host?

**Comment by tfenster** [comment]
@weijuans-msft I gave it a try again and it now works! For anyone having the same issue: My host has Kernel Version `10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)` and Operating System `Windows Server Datacenter Version 2004 (OS Build 19041.867)`. The windows servercore image has OS version `10.0.19041.867`
